### ISSUE TITLE
Can not find arg.adv_targeted in code

### ISSUE THREAD

**Issue by Kris-Lcq** [SCLBD/Transfer_attack_RAP#1]
Can not find arg.adv_targeted in code

**Comment by Alan-Qin** [comment]
Sorry about this issue. Actually, we do not use this arg.adv_targeted parameter in the final version. Therefore, you could just delete it. It is not used in pgd function either. 

Zeyu

**Comment by Alan-Qin** [comment]
I am sorry about my previous mistakes. I have updated the codes. If having other questions, please contact me again.

Zeyu
