### ISSUE TITLE
About Runing

### ISSUE THREAD

**Issue by ylhz** [SCLBD/Transfer_attack_RAP#2]
Hello! Nice to read such interesting work!

It seems that your code cannot be run directly, and the result after I tried to modify it is too different from the paper. Can you please improve the code?

Thanks~

**Comment by Alan-Qin** [comment]
Could you please show the details about failed cases?

**Comment by ylhz** [comment]
Thanks for your reply.

The result after I modified the code is as follows. 

The attack success rate of 10 iterations in the no-target attack differs significantly from the paper.

* The targeted attack success rate (%) of all baseline attacks with RAP. The results
with logit loss and 10/100/200/300/400 iterations are reported.

|method | ResNet50*|Inc-v3|DesneNet-121|VGG-16|
|-|-|-|-|-|
MI+RAP-LS(paper)|-/-/-/-/                     | 0.1 / 0.1 / 1.4 / 1.6 / 2.4 | 3.4 / 6.3 / 25.9 / 28.9 / 29.6 | 1.2 / 2.1 / 18.2 / 20.0 / 20.6 |
MI+RAP-LS(my)   | 5.6 / 99.1 / 99.499.4 / 99.3 | 0.0 / 0.1 / 1.7 / 2.0 / 1.9 | 0.0 / 6.3 / 24.5 / 29.2 / 29.6 | 0.0 / 2.2 / 16.8 / 21.1 / 20.3 |

* The untargeted attack success rate (%) of all baseline attacks with RAP.  The results with
CE loss and 10/100/200/300/400 iterations are reported.

|method | ResNet50*|Inc-v3|DesneNet-121|VGG-16|
|-|-|-|-|-|
|MI+RAP-LS(paper)| -/-/-/-/  | 53.2 / 50.7 / 64.3 / 73.6 / 77.4 | 87.3 / 85.4 / 90.8 / 95.0 / 96.1 | 82.5 / 82.8 / 89.3 / 93.7 / 94.5 |
|MI+RAP-LS(my)   | 94.8 / 100 / 100 / 100 / 100 /  | **9.3** / 50.9 / 62.0 / 64.2 / 64.4   | **19.8** / 85.5 / 92.8 / 94.5 / 95.5   |  **26.3** / 82.0 / 92.2 / 93.1 / 92.9   |

**Comment by Alan-Qin** [comment]
Please notice that in our paper, we set the iteration number as 300 following the previous NeurIPS 2021 paper. We also highlight this part in our experimental setting. 

Thanks,

Zeyu

**Comment by Alan-Qin** [comment]
This is very weird.... Because of choosing the LS strategy, we will not take RAP during the first 100 iterations. Therefore, we just use the original method.

**Comment by ylhz** [comment]
Thank you very much for the reminder. I have carefully checked and the problem is indeed with my code. It is now fixed. 

I still hope you can update the code to help other researchers to be able to run it directly.

**Comment by Alan-Qin** [comment]
Thanks for your suggestion! I will update them ^_^. 

Zeyu
