### ISSUE TITLE
About Figure 3

### ISSUE THREAD

**Issue by tuoli9** [SCLBD/Transfer_attack_RAP#3]
Could you provide the code to draw Figure 3？

**Comment by Alan-Qin** [comment]
Hi,  I have mentioned the details about how to implement visualizations in appendix.

<img width="911" alt="image" src="https://github.com/SCLBD/Transfer_attack_RAP/assets/43122728/8de20564-b219-43f2-84de-74ebd3421036">

Bests,
Zeyu
