### ISSUE TITLE
关于图一

### ISSUE THREAD

**Issue by cuiyan2000** [SCLBD/Transfer_attack_RAP#4]
很抱歉我的才疏学浅，我在阅读您的论文和代码的时候遇到了一些问题，请赐教

**Comment by cuiyan2000** [comment]
您在文章3.2部分中说xadv附近的点也具有类似xadv的低损失值，怎么证明最小化损失后的的Xadv是位于平坦的局部区域。
对于图一，可以看到xpgd位于局部极值点，如何保证在最小化损失时，它不会落入局部极值点xpgd，而是落入期望的平坦的局部区域xadv。

**Comment by Alan-Qin** [comment]
We have provided empirical evidence about the local flatness of x_adv in Figure 3. We believe min-max optimization could help achieve this goal.

**Comment by cuiyan2000** [comment]
对于图一，为什么反向加噪声之后到了左边的点（xt+nrap）那里？那优化的时候不还是会陷入尖锐的点（xpgd）吗？
